version: '3.7'

services:
  caddy:
    image: caddy:2.4.1
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../portfolio/build:/portfolio
      - caddy_data:/data
      - caddy_config:/config

  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    env_file:
      - '.env'
    volumes:
      - ./ddclient-config:/config
    restart: always

  finances-app:
    image: elijah415hz/finances-flask
    restart: always
    ports:
      - 8000:8000
    env_file:
      - '.env'
    volumes:
      - ../finances-flask:/usr/src/app

  finances-db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    volumes:
      - finances-db:/config
      - ../finances-flask/db:/config/initdb.d/
    env_file:
      - '.env'
    ports:
      - 3306:3306

  cron:
    image: elijah415hz/finances-cron
    restart: always
    volumes:
      - ../finances-flask/cron:/usr/src/cron
    env_file:
      - '.env'

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - 8080:80
      - 3012:3012
    volumes:
      - ./bw-data:/data

  nextcloud_db:
    image: linuxserver/mariadb:arm32v6-latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TulipHyacinth
      - MYSQL_PASSWORD=TulipHyacinth080518
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8081:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=TulipHyacinth080518
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db

volumes:
  caddy_data:
  caddy_config:
  nextcloud:
  db:
  finances-db:
