version: '3.7'

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../portfolio/build:/portfolio
      - ../finances-flask/build:/finances
      - ./bind-mounts/caddy/caddy_data:/data
      - ./bind-mounts/caddy/caddy_config:/config
      - ../caddy_logs:/var/log

  ddclient:
    image: ghcr.io/linuxserver/ddclient
    restart: always
    container_name: ddclient
    env_file:
      - 'finances.env'
    volumes:
      - ./ddclient-config:/config

  finances-app:
    image: elijah415hz/finances-flask:arm64
    restart: always
    env_file:
      - 'finances.env'
    volumes:
      - ../finances-flask:/usr/src/app

  finances-db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    volumes:
      - ./bind-mounts/finances-db/config:/config
      - ./bind-mounts/finances-db/db-files:/var/lib/mysql
      - ../finances-flask/db:/docker-entrypoint-initdb.d
    env_file:
      - 'finances.env'

  cron:
    image: elijah415hz/finances-cron:arm64
    restart: always
    volumes:
      - ../finances-flask/cron:/usr/src/cron
    env_file:
      - 'finances.env'

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    volumes:
      - ./bind-mounts/bw-data:/data

  nextcloud_db:
    image: linuxserver/mariadb:arm64v8-latest
    restart: always
    volumes:
      - ./bind-mounts/nextcloud_db:/var/lib/mysql
    env_file:
      - 'nextcloud.env'

  nextcloud:
    image: nextcloud:23
    restart: always
    volumes:
      - ./bind-mounts/nextcloud:/var/www/html
    env_file:
      - 'nextcloud.env'

  collabora:
    image: collabora/code:latest
    restart: always
    env_file:
      - 'nextcloud.env'
    volumes:
      - ./coolwsd.xml:/etc/coolwsd/coolwsd.xml

  jellyfin:
    image: jellyfin/jellyfin
    restart: always
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./bind-mounts/jellyfin/config:/config
      - ./bind-mounts/jellyfin/cache:/cache
      - ./bind-mounts/nextcloud/data/blarvis/files/media:/media:ro
    env_file:
      - 'jellyfin.env'
