version: '3.7'

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../portfolio/build:/portfolio
      - ../finances-flask/build:/finances
      - ./bind-mounts/caddy/caddy_data:/data
      - ./bind-mounts/caddy/caddy_config:/config
      - ../caddy_logs:/var/log

  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    env_file:
      - '.env'
    volumes:
      - ./ddclient-config:/config
    restart: always

  finances-app:
    image: elijah415hz/finances-flask:arm64
    restart: always
    env_file:
      - '.env'
    volumes:
      - ../finances-flask:/usr/src/app

  finances-db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    volumes:
      - ./bind-mounts/finances-db/config:/config
      - ./bind-mounts/finances-db/db-files:/var/lib/mysql
      - ../finances-flask/db:/docker-entrypoint-initdb.d
    env_file:
      - '.env'

  cron:
    image: elijah415hz/finances-cron:arm64
    restart: always
    volumes:
      - ../finances-flask/cron:/usr/src/cron
    env_file:
      - '.env'

  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - 8080:80
      - 3012:3012
    volumes:
      - ./bind-mounts/bw-data:/data

  nextcloud_db:
    image: linuxserver/mariadb:arm64v8-latest
    restart: always
    volumes:
      - ./bind-mounts/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TulipHyacinth
      - MYSQL_PASSWORD=TulipHyacinth080518
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - ./bind-mounts/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=TulipHyacinth080518
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_db

  collabora:
    image: collabora/code:latest
    restart: always
    environment:
      - password=collaboratingInCloster080518
      - username=blarffice
      - domain=office.elijahblaisdell.dev
      - extra_params=--o:ssl.enable=true
    ports:
      - 9980:9980
