version: '3.7'

services:
  caddy:
    image: caddy:latest
    # networks:
    #   - caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./portfolio/build:/portfolio
      - ./finances-flask/build:/finances
      - ./bind-mounts/caddy/caddy_data:/data
      - ./bind-mounts/caddy/caddy_config:/config
      - ./bind-mounts/caddy/caddy_logs:/var/log

  ddclient:
    image: ghcr.io/linuxserver/ddclient:v3.9.1-ls100
    restart: always
    container_name: ddclient
    env_file:
      - 'finances.env'
    volumes:
      - ./ddclient-config:/config

  finances-app:
    image: elijah415hz/finances-flask:arm64
    # networks:
    #   - caddy
    #   - finances
    restart: always
    env_file:
      - 'finances.env'
    volumes:
      - ./finances-flask:/usr/src/app

  finances-db:
    image: ghcr.io/linuxserver/mariadb
    # networks:
    #   - finances
    restart: always
    volumes:
      - ./bind-mounts/finances-db/config:/config
      - ./finances-flask/db:/config/initdb.d
    env_file:
      - 'finances.env'

  finances-cron:
    image: elijah415hz/finances-cron:arm64
    # networks:
    #   - finances
    restart: always
    volumes:
      - ./finances-flask/cron:/usr/src/cron
    env_file:
      - 'finances.env'

  nextcloud:
    image: nextcloud:25
    # networks:
    #   - caddy
    #   - nextcloud
    restart: always
    volumes:
      - ./bind-mounts/nextcloud:/var/www/html
    env_file:
      - 'nextcloud.env'

  nextcloud_db:
    image: linuxserver/mariadb:arm64v8-latest
    # networks:
    #   - nextcloud
    restart: always
    volumes:
      - ./bind-mounts/nextcloud_db:/config
      - ./bind-mounts/nextcloud-db-backup:/config/initdb.d
    env_file:
      - 'nextcloud.env'

  nextcloud-cron:
    image: nextcloud:25
    restart: always
    # networks:
    #   - nextcloud
    volumes:
      - ./bind-mounts/nextcloud:/var/www/html
    entrypoint: /cron.sh

  collabora:
    image: collabora/code:latest
    # networks:
    #   - caddy
    #   - nextcloud
    restart: always
    env_file:
      - 'nextcloud.env'
    volumes:
      - ./collabora-config/coolwsd.xml:/etc/coolwsd/coolwsd.xml

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    env_file:
      - 'onlyoffice.env'
    volumes:
      - ./bind-mounts/onlyoffice/document_data:/var/www/onlyoffice/Data
      - ./bind-mounts/onlyoffice/document_log:/var/log/onlyoffice

  jellyfin:
    image: jellyfin/jellyfin:latest
    # networks:
    #   - caddy
    restart: always
    container_name: jellyfin
    volumes:
      - ./bind-mounts/jellyfin/config:/config
      - ./bind-mounts/jellyfin/cache:/cache
      - ./bind-mounts/nextcloud/data/blarvis/files/Media:/media
    env_file:
      - 'jellyfin.env'

  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    # networks:
    #   - caddy
    restart: always
    env_file:
      - 'nightscout.env'

  cloud-backup-cron:
    build: .
    entrypoint: crond -l 2 -f
    volumes:
      - ./:/usr/ServerBackup
      - ./rclone:/config/rclone
      - ./rclone/data:/data
      - ./backup.sh:/etc/periodic/daily/backup.sh
    env_file:
      - 'nextcloud.env'
      - 'cloud-backup-cron.env'

  # bitwarden:
  #   image: vaultwarden/server:latest
  #   # networks:
  #   #   - caddy
  #   container_name: bitwarden
  #   restart: always
  #   volumes:
  #     - ./bind-mounts/bw-data:/data

# networks:
#   caddy:
#     external: true
#   nextcloud:
#   finances:
